hydra:
  run:
    dir: ${base_dir}/${results_subdir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${base_dir}/${results_subdir}/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - model=astgcn_like
    - training.n_epochs=10
    - data=all_vars
    - optuna.enabled=True
  job:
    name: tune_models
    chdir: null
    override_dirname: data=all_vars,model=astgcn_like,optuna.enabled=True,training.n_epochs=10
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/nick/bachelor-project/third-copy
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/nick/bachelor-project/third-copy/src/graph_modelling/scripts/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      model: astgcn_like
      data: all_vars
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
data:
  only_no2: false
  num_vars: 7
  cache_file: no2_dataset_cache.pkl
  force_reload: false
  sample_size: 1.0
  shuffle: true
  ratio:
  - 0.7
  - 0.15
  - 0.15
model:
  _target_: src.graph_modelling.models.astgcn.ASTGCN_Like
  block_channels: 32
  gru_channels: 32
  K: 1
  num_blocks: 2
seed: 34
base_dir: .
results_subdir: comparison_results
training:
  n_lags: 72
  n_horizon: 24
  batch_size: 16
  n_step: 24
  n_epochs: 10
  patience: 5
optuna:
  enabled: true
  study_name: no2_model_optimization
  storage: sqlite:///no2_models_optuna.db
  n_trials: 50
  timeout: 72000
  direction: minimize
paths:
  model_save_name: final_model.pt
  history_save_name: training_history.json
  metrics_save_name: test_metrics.json
  tensorboard_subdir: tensorboard_logs
  plot_subdir: plots
  optuna_subdir: optuna_results
